### ISSUE TITLE
Error updating data in databaseMongoError: cannot use the part (YouTube of APIs.YouTube.access_token) to traverse the element ({YouTube: ""})

### ISSUE THREAD

**Issue by NateFuller** [TeamPelican/QueueUp#4]
Encountered this error when attempting to authenticate a user. Occurs after going to Google and selecting a user account to affiliate with YT and then being sent back to QueueUp.

![mongo_err01](https://cloud.githubusercontent.com/assets/4147804/11762552/a0ea7ec4-a0b8-11e5-828f-29b9ddc9e7b5.png)

**Comment by NateFuller** [comment]
This occurs because you can only attempt to access the .access_token of APIs.YouTube if APIs.YouTube is of type object. Because it is initialized to "", it is of type string. A proposal to fix would be to initialize all APIs.<ServiceName> fields to {} instead of to "".

**Comment by NateFuller** [comment]
Further investigation, switching to {} worked, but refresh token isn't being returned by API call so we fail a && check on line ~184 of MongoDB-user.js

**Comment by NateFuller** [comment]
Example response from oauth2Client.getToken from line 129 in routes/user.js.

```
{
   access_token: <access_token_here>,
   token_type: 'Bearer',
   expiry_date: 1449939915416
}
```

Implementation of OAuth2Client.getToken() can be seen [here](https://github.com/google/google-auth-library-nodejs/blob/master/lib/auth/oauth2client.js#L133). You'll see that it doesn't set a refresh token.

**Comment by xuan7016** [comment]
fixed in latest commit
